name: Sign APK

on:
workflow_dispatch:

jobs:
  sign:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'  # 设置为您项目所需的 Java 版本

      - name: Build the project
        run: ./gradlew assembleRelease  # 根据您的项目构建命令进行调整

      - name: Sign APK
        env:
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        run: |
          # 使用 jarsigner 对 APK 进行签名
          jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 \
            -keystore my-release-key.jks \
            -storepass $KEYSTORE_PASSWORD \
            -keypass $KEY_PASSWORD \
            app/build/outputs/apk/release/app-release-unsigned.apk \
            $KEY_ALIAS

      - name: Zip signed APK
        run: |
          mkdir signed_apk
          cp app/build/outputs/apk/release/app-release-unsigned.apk signed_apk/
          cp app/build/outputs/apk/release/app-release.apk signed_apk/
          zip -r signed_apk.zip signed_apk/
          
      - name: Upload signed APK
        uses: actions/upload-artifact@v2
        with:
          name: signed-apk
          path: signed_apk.zip
