name: 58LA Crawler Workflow

on:
  schedule:
    - cron: '0 0 * * *'  # 每天午夜执行
  workflow_dispatch:  # 允许手动触发

jobs:
  crawl:
    runs-on: ubuntu-18.04  # 使用Ubuntu 18.04，它包含libgconf-2-4包
    steps:
      - name: 检出代码
        uses: actions/checkout@v3

      - name: 设置Python环境
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # 使用Python 3.9

      - name: 安装系统依赖
        run: |
          sudo apt-get update
          sudo apt-get install -y libgconf-2-4
          # 安装Chrome浏览器用于Selenium
          sudo apt-get install -y google-chrome-stable

      - name: 安装Python依赖
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: 运行爬虫脚本
        run: python 58LA.py

      - name: 上传结果文件
        uses: actions/upload-artifact@v3
        with:
          name: subscription-links
          path: links.txt
