name: 定时运行爬虫脚本

on:
  schedule:
    # 每天凌晨2点运行（UTC时间，北京时间+8小时）
    - cron: '0 18 * * *'
  workflow_dispatch:  # 允许手动触发

jobs:
  crawl:
    runs-on: ubuntu-latest

    steps:
    - name: 检出代码
      uses: actions/checkout@v4

    - name: 设置Python环境
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: 安装依赖
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: 运行爬虫脚本
      env:
        # 可选：添加代理配置
        #PROXY: ${{ secrets.PROXY }}
      run: python 58LA.py

    - name: 提交更新的links.txt文件
      if: always()
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git add links.txt
        git commit -m 'Update links.txt' || echo 'No changes to commit'
        git push origin main
