name: Sign and Release APK

on:
  workflow_dispatch:

jobs:
  sign-and-release:
    runs-on: ubuntu-latest
    steps:
      # Step 1: 克隆仓库
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: 设置 JDK
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'

      # Step 3: 对 APK 进行签名
      - name: Sign APK
        env:
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        run: |
          jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 \
            -keystore my-release-key.jks \
            -storepass $KEYSTORE_PASSWORD \
            -keypass $KEY_PASSWORD \
            智远TV_6.0.3.apk \
            $KEY_ALIAS

      # Step 4: 压缩签名后的 APK
      - name: Zip signed APK
        run: |
          mkdir signed_apk
          cp 智远TV_6.0.3.apk signed_apk/
          zip -r signed_apk.zip signed_apk/

      # Step 5: 上传签名后的 APK 作为 Artifact
      - name: Upload signed APK
        uses: actions/upload-artifact@v4.6.0
        with:
          name: signed-apk
          path: signed_apk.zip

      # Step 6: 创建 GitHub Release 并发布 APK
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v6.0.3  # 替换为你的版本号
          release_name: Release v6.0.3  # 替换为你的发布名称
          body: |
            这是一个自动生成的发布版本。
            files: 
            - signed_apk.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
