name: R2

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */4 * * *'  # UTC 22:00 触发，北京时间 6:00

jobs:
  upload-to-r2:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install puppeteer-extra and stealth plugin
        run: npm install puppeteer-extra puppeteer-extra-plugin-stealth puppeteer

      - name: Run Puppeteer to fetch dy.txt.txt from multiple URLs
        env:
          TARGET_URLS: |
             https://dy.51281868.xyz/yuanzhou029?b64
          OUTPUT_FILE: "dy.txt"
        run: node fetch_clash.js

      - name: Install AWS CLI
        run: |
          sudo apt-get update && sudo apt-get install -y python3-pip
          pip3 install awscli --upgrade

      - name: Upload dy.txt.txt to Cloudflare R2
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.CLOUDFLARE_R2_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.CLOUDFLARE_R2_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1
          AWS_ENDPOINT_URL: ${{ secrets.CLOUDFLARE_R2_ENDPOINT }}
          BUCKET_NAME: ${{ secrets.CLOUDFLARE_R2_BUCKET_NAME }}
        run: |
          aws s3 cp dy.txt.txt s3://$BUCKET_NAME/dy.txt.txt --endpoint-url $AWS_ENDPOINT_URL
