name: IPTV-Cloudflare R2

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
  push:

jobs:
  upload-to-r2:
    runs-on: ubuntu-latest

    steps:
      - name: Download file from GitHub
        run: |
          curl -o result.txt https://raw.githubusercontent.com/8080713/iptv-api/refs/heads/main/output/result.txt

      - name: Install AWS CLI
        run: |
          sudo apt-get update && sudo apt-get install -y python3-pip
          pip3 install awscli --upgrade

      - name: Upload file to Cloudflare R2
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.CLOUDFLARE_R2_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.CLOUDFLARE_R2_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1
          AWS_ENDPOINT_URL: ${{ secrets.CLOUDFLARE_R2_ENDPOINT }}
          BUCKET_NAME: ${{ secrets.CLOUDFLARE_R2_BUCKET_NAME }}
        run: |
          aws s3 cp result.txt s3://$BUCKET_NAME/result.txt --endpoint-url $AWS_ENDPOINT_URL
