name: IPTV-Cloudflare R2

on:
  # 手动触发
  workflow_dispatch:
  # 定时触发（每天 UTC 00:00）
  schedule:
    - cron: '0 0 * * *'
  # 推送到任何分支时触发
  push:

jobs:
  upload-to-r2:
    runs-on: ubuntu-latest

    steps:
      # Step 1: 下载指定文件
      - name: Download file from GitHub
        run: |
          curl -o result.txt https://raw.githubusercontent.com/8080713/iptv-api/refs/heads/main/output/result.txt

      # Step 2: 安装 AWS CLI（用于操作 Cloudflare R2）
      - name: Install AWS CLI
        run: |
          sudo apt-get update && sudo apt-get install -y awscli

      # Step 3: 配置 AWS CLI 以连接到 Cloudflare R2
      - name: Configure AWS CLI for Cloudflare R2
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.CLOUDFLARE_R2_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.CLOUDFLARE_R2_SECRET_ACCESS_KEY }}
          AWS_ENDPOINT: ${{ secrets.CLOUDFLARE_R2_ENDPOINT }}
        run: |
          aws configure set default.region us-east-1
          aws configure set default.s3.addressing_style path

      # Step 4: 上传文件到 Cloudflare R2
      - name: Upload file to Cloudflare R2
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.CLOUDFLARE_R2_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.CLOUDFLARE_R2_SECRET_ACCESS_KEY }}
          AWS_ENDPOINT: ${{ secrets.CLOUDFLARE_R2_ENDPOINT }}
        run: |
          aws s3 cp result.txt s3://your-bucket-name/result.txt

  # 任务：清除工作流运行记录
  cleanup-workflow-runs:
    runs-on: ubuntu-latest
    needs: upload-to-r2

    steps:
      # Step 1: 设置 GitHub 访问令牌
      - name: Setup GitHub Token
        id: setup-github-token
        run: |
          echo "GH_TOKEN=${{ secrets.GITHUB_TOKEN }}" >> $GITHUB_ENV

      # Step 2: 安装 jq
      - name: Install jq
        run: sudo apt-get install -y jq

      # Step 3: 删除工作流运行记录
      - name: Delete workflow runs
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # 获取当前工作流的所有运行记录
          RUNS=$(curl -s -H "Authorization: token $GH_TOKEN" \
            "https://api.github.com/repos/${{ github.repository }}/actions/runs?per_page=100" | jq '.workflow_runs[] | select(.status == "completed") | .id')

          # 遍历并删除每个运行记录
          for RUN_ID in $RUNS; do
            echo "Deleting run ID: $RUN_ID"
            curl -X DELETE -H "Authorization: token $GH_TOKEN" \
              "https://api.github.com/repos/${{ github.repository }}/actions/runs/$RUN_ID"
          done
