name: VLESS-Cloudflare KV

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */4 * * *'  # 每4小时触发一次

jobs:
  upload-to-r2:
    runs-on: ubuntu-latest
    permissions:
      contents: write 

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install requests
        sudo apt-get update && sudo apt-get install -y python3-pip
        pip3 install awscli --upgrade
        pip install requests
        pip install telethon

    - name: Run Python script
      run: |
        python get_subscription.py
        python get_token.py
  

    - name: Run scraping script
      env:
        TELEGRAM_API_ID: ${{ secrets.TELEGRAM_API_ID }}
        TELEGRAM_API_HASH: ${{ secrets.TELEGRAM_API_HASH }}
        TELEGRAM_SESSION_STRING: ${{ secrets.TELEGRAM_SESSION_STRING }}
        run: python 12.py  # 调整为仓库内实际路径（如文件在根目录可简化为 python 12.py）


    - name: 运行 KV 同步脚本
      env:
          # 从 GitHub Secrets 注入环境变量（需提前在仓库 Settings > Secrets 中配置）
        CF_EMAIL: ${{ secrets.CF_EMAIL }}
        CF_API_KEY: ${{ secrets.CF_API_KEY }}
        CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
        CF_KV_NAMESPACE_ID: ${{ secrets.CF_KV_NAMESPACE_ID }}
        CF_KV_KEY: "LINK.txt"  # 可选，若需修改键名可调整
        run: python kv.py  # 注意路径与仓库结构匹配（若脚本在根目录则改为 python KV.py）

    - name: Commit and push changes
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add links.txt
        git commit -m "Update links.txt with valid URLs"
        git push  

        
          
