name: Telegram 订阅链接抓取

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  scrape-links:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # 关键：授予仓库内容写入权限

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true  # 保留认证凭证（默认已开启，显式声明确保兼容）

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install telethon
          pip install requests

      - name: Run scraping script
        env:
          TELEGRAM_API_ID: ${{ secrets.TELEGRAM_API_ID }}
          TELEGRAM_API_HASH: ${{ secrets.TELEGRAM_API_HASH }}
          TELEGRAM_SESSION_STRING: ${{ secrets.TELEGRAM_SESSION_STRING }}
        run: python 12.py  # 调整为仓库内实际路径（如文件在根目录可简化为 python 12.py）

      - name: Commit and push links.txt
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Actions"
          git add links.txt
          git commit -m "自动更新订阅链接（GitHub Actions）" || echo "无文件变更"
          git push
